-- CX Reply Assistant: initial schema.
-- Ids are generated by the application (prefixed strings) so the in-memory and
-- Postgres adapters behave identically. Every tenant-owned row carries brand_id
-- so brand scoping can be enforced in queries today and by RLS later.

create table if not exists brands (
  id            text primary key,
  slug          text not null unique,
  name          text not null,
  description   text not null default '',
  tone          text not null default '',
  support_email text not null default '',
  accent_color  text not null default '#334155',
  created_at    timestamptz not null default now()
);

create table if not exists kb_entries (
  id         text primary key,
  brand_id   text not null references brands(id) on delete cascade,
  category   text not null check (category in ('returns','refunds','shipping','cancellations','general')),
  title      text not null,
  content    text not null,
  tags       jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists kb_entries_brand_idx on kb_entries(brand_id);

create table if not exists customers (
  id       text primary key,
  brand_id text not null references brands(id) on delete cascade,
  name     text not null,
  email    text not null default '',
  phone    text not null default ''
);
create index if not exists customers_brand_idx on customers(brand_id);

create table if not exists orders (
  id           text primary key,
  brand_id     text not null references brands(id) on delete cascade,
  customer_id  text not null references customers(id) on delete cascade,
  order_number text not null,
  status       text not null check (status in ('processing','shipped','delivered','cancelled','refunded')),
  items        jsonb not null default '[]'::jsonb,
  total        numeric(12,2) not null default 0,
  currency     text not null default 'INR',
  ordered_at   timestamptz not null,
  shipped_at   timestamptz,
  delivered_at timestamptz
);
create index if not exists orders_customer_idx on orders(customer_id);

create table if not exists conversations (
  id          text primary key,
  brand_id    text not null references brands(id) on delete cascade,
  customer_id text not null references customers(id) on delete cascade,
  order_id    text references orders(id) on delete set null,
  channel     text not null check (channel in ('whatsapp','email','web')),
  status      text not null default 'open' check (status in ('open','resolved')),
  subject     text not null default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists conversations_brand_idx on conversations(brand_id);
create index if not exists conversations_updated_idx on conversations(updated_at desc);

create table if not exists messages (
  id              text primary key,
  conversation_id text not null references conversations(id) on delete cascade,
  sender          text not null check (sender in ('customer','agent')),
  body            text not null,
  source          text not null default 'human' check (source in ('human','ai_approved','ai_edited')),
  generation_id   text,
  created_at      timestamptz not null default now()
);
create index if not exists messages_conversation_idx on messages(conversation_id, created_at);

-- Audit log of every AI generation: what the customer said, what knowledge was
-- retrieved, what the model produced, what the agent changed, and what was sent.
create table if not exists ai_generations (
  id                    text primary key,
  conversation_id       text not null references conversations(id) on delete cascade,
  brand_id              text not null references brands(id) on delete cascade,
  customer_message_id   text,
  customer_message      text not null,
  retrieval_query       text not null default '',
  retrieval_status      text not null check (retrieval_status in ('found','weak','none')),
  retrieved_context     jsonb not null default '[]'::jsonb,
  provider              text not null,
  model                 text not null,
  prompt_tokens         integer,
  completion_tokens     integer,
  latency_ms            integer not null default 0,
  ai_response           text not null,
  assessment            jsonb not null,
  flags                 jsonb not null default '[]'::jsonb,
  agent_instruction     text,
  agent_edited_response text,
  final_response        text,
  status                text not null default 'draft' check (status in ('draft','approved','discarded','superseded')),
  created_at            timestamptz not null default now(),
  resolved_at           timestamptz
);
create index if not exists ai_generations_conversation_idx on ai_generations(conversation_id, created_at desc);
create index if not exists ai_generations_brand_idx on ai_generations(brand_id, created_at desc);
